### ISSUE TITLE
💜✨Feature proposal✨💜 - Keyframe Keymap option

### ISSUE THREAD

**Issue by diegodelarocha** [pablodp606/keymesh-addon#14]
Hi there, this add-on is lovely 💜, is there a chance you could implement a shortcut for `Keyframe Mesh` ? If this is the case can it be mapped by the user? This would be super appreciated for speeding up workflow! 🤓✨

**Comment by diegodelarocha** [comment]
Ah nevermind, I didn't know you could right click on any button in blender and assign a shortcut 🤓!

Regardless though it might be a nice quality of life to add as a default for users since we are all dumb :P

Here's an example of my keybinds:

![Keyframe Mesh ShortCut](https://user-images.githubusercontent.com/20521814/117552274-28be1800-afff-11eb-817e-8444e311f8b6.png)

**Comment by aldrinmathew** [comment]
@diegodelarocha

There already is a shortcut for the Keymesh feature, in my fork of the addon.

https://github.com/AldrinMathew/keymesh-addon

**Comment by diegodelarocha** [comment]
oh cool! which one should we be following as the main plug-in? 🤓

**Comment by aldrinmathew** [comment]
You can use that fork without any problem. It's a few commits ahead of this repo. The original developer of Keymesh is Pablo Dobarro and the last time I checked, he is busy with some internal tasks in Blender. This repo hasn't got any attention since the release.

**Comment by diegodelarocha** [comment]
Ah cool, I'll do so, is it hard to have the shortcut changeable by the user? 🤓

Just took a look, I like that the `Keyframe Mesh` button is a bit bigger :), I'll report back on the other repo if i find any bugs :)

**Comment by aldrinmathew** [comment]
@diegodelarocha 

Just tested it. Blender have a native functionality to assign shortcuts. So it works.
Yah, I made the button bigger just to increase accessibility and give more importance. Feel free to report issues anytime, no matter how small or big. I am a python novice, but I will try my best to fix it.

**Comment by diegodelarocha** [comment]
Oh great thanks! Yeh, just tested your fork, and it worked perfect, so I'll keep going with that one 🤓 . Thanks!
